### ISSUE TITLE
Arabic word printing issue

### ISSUE THREAD

**Issue by pandiarajanvp** [andrey-ushakov/esc_pos_printer#18]
How can print Arabic words?

**Comment by andrey-ushakov** [comment]
Hi @pandiarajanvp ,

I would say it really depends on you printer model.
Try to print the printer configuration (you can find on Google how to do that for your model) and find the corresponding code for the Arabic language.

After that you can add a new code table under enums.dart / PosCodeTable class.

It will be something like this:
```
/// Arabic
static const arabic = PosCodeTable._internal(<printer code>);
```


After that try to print like this:
`printer.println('<arabic text>', styles: PosStyles(codeTable: PosCodeTable.arabic));`

I hope it will be helpful :)

**Comment by DJafari** [comment]
@andrey-ushakov any update about this issue ?

**Comment by andrey-ushakov** [comment]
Hi @DJafari,

It happens because a standard dart's latin1 codec is currently used to convert strings from Unicode to an appropriate code table.

You can check how it works to print the text in Chinese with a custom [gbk_codec](https://pub.dev/packages/gbk_codec).

So I believe to resolve this problem, a new codec Unicode <--> Arabic code table should be written. Or probably there is already an appropriate package (just like for Chinese).

Hope it helps!

**Comment by andrey-ushakov** [comment]
Hi,
Now it should be possible to print Arabic texts, here are some examples for other languages:
https://github.com/andrey-ushakov/esc_pos_printer#using-code-tables
Unfortunately, my printer doesn't support Arabic so I can't really test it...

Feel free to reopen the issue if you have any further questions

**Comment by Ashbuhrz** [comment]
Still not possible
