### ISSUE TITLE
Paper size calculation is wrong?

### ISSUE THREAD

**Issue by KyawNaingTun** [andrey-ushakov/esc_pos_printer#59]
**Printer**: Star BSC-10
**Version**: esc_pos_printer: ^3.1.4
**Paper size**: 80mm

**My code**
`const PaperSize paper = PaperSize.mm80;`
`final PosPrintResult res = await printerManager.printTicket(await demoReceipt(paper));`

How can I fix it? Please give me any suggestions here.
 
After print out the receipt, I got the following link this
![printer-img](https://user-images.githubusercontent.com/6079250/77221883-4bcc0500-6b7c-11ea-92f0-ab49af8af769.png)

**Comment by andrey-ushakov** [comment]
It seems that your printer with current settings can print only 42 characters/line.

I'm aware of this and will try to update the library soon in order to make it possible to choose the ticket line length in characters (and not it mm).

But you could try to change the font. In general, POS/ESC printers have at least 2 fonts - A and B. You can pass the `PosFontType.fontB` into `PosStyles`. It may help.

**Comment by andrey-ushakov** [comment]
Hi there, 

Have you tried the latest version of the library? Now you should be able to config the max characters number per line for your printer's font.

**Comment by KyawNaingTun** [comment]
@andrey-ushakov  Thanks for your reply. I will give you an answer after I do it again.
